### ISSUE TITLE
Bug: NPM install not working

### ISSUE THREAD

**Issue by fullopt** [eslint/css#14]
### Environment

ESLint version: v9.15.0
@eslint/css version: latest
Node version: v20.18.0
npm version: 10.8.2
Operating System: macOS Sequoia

### Which language are you using?

stylesheet

### What did you do?

Hi, I tried to install via NPM as described in readme:

npm install @eslint/css -D

### What did you expect to happen?

I expected to install the NPM package.

### What actually happened?

but I've got error E404:

npm error code E404
npm error 404 Not Found - GET https://registry.npmjs.org/@eslint%2fcss - Not found
npm error 404
npm error 404  '@eslint/css@*' is not in this registry.

### Link to Minimal Reproducible Example

https://nodomain

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

Is this repo WIP or what is the reason the package is not available?
If so, where can I find info about the date of release?
Thank you.

**Comment by nzakas** [comment]
The package hasn't been released yet. Hopefully some time next week.
