### ISSUE TITLE
Change Request: linting CSS templates

### ISSUE THREAD

**Issue by yinonov** [eslint/css#25]
### Environment

ESLint version: 
@eslint/css version: 0.1.0

### What problem do you want to solve?

The CSS plugin currently support only linting CSS files

### What do you think is the correct solution?

I’d like the CSS plugin to support linting CSS templates in different variations, one of which could be CSS in a template literal form

### Participation

- [ ] I am willing to submit a pull request for this change.

### Additional comments

Haven’t ticked the “willing to submit PR…” as am not familiar with the codebase. Wouldn't mind to with partial support from the maintaining team

**Comment by nzakas** [comment]
Sorry, I'm not quite sure what it is you're asking for. Can you explain more and give some examples?

**Comment by nzakas** [comment]
No response, so closing.
