### ISSUE TITLE
Bug: typescript type for css.configs.recommended is incorrect

### ISSUE THREAD

**Issue by timheilman** [eslint/css#31]
### Environment

ESLint version: 
@eslint/css version: 0.1.0
Node version: v20.9.0
npm version: 10.1.0
Operating System: Mac OS X

### Which language are you using?

stylesheet

### What did you do?

<details>
<summary>Configuration</summary>

Exactly as in the documentation, except with `// @ts-check` at top of file:

eslint.config.mjs:
```
// @ts-check

import css from "@eslint/css";

export default [
  {
    files: ["**/*.css"],
    language: "css/css",
    ...css.configs.recommended,
  },
];
```
</details>

```js
(not relevant)
```

Gives typescript error:

`Property 'recommended' does not exist on type '{}'.ts(2339)`

This is because  `node_modules/@eslint/css/dist/esm/index.d.ts` has this line:
```
declare namespace plugin {
    ...
    let configs: {};
}
```

Whereas one more specific expected type would be:

```
declare namespace plugin {
    ...
    let configs: {
        recommended: {
            rules: {
                "css/no-empty-blocks": string;
                "css/no-duplicate-imports": string;
                "css/no-invalid-at-rules": string;
                "css/no-invalid-properties": string;
            };
        }
    };
}
```

I suspect this could be achieved with the current type generation mechanism by replacing this block in `index.js`:

```
const plugin = {
	meta: {
		name: "@eslint/css",
		version: "0.1.0", // x-release-please-version
	},
	languages: {
		css: new CSSLanguage(),
	},
	rules: {
		"no-empty-blocks": noEmptyBlocks,
		"no-duplicate-imports": noDuplicateImports,
		"no-invalid-at-rules": noInvalidAtRules,
		"no-invalid-properties": noInvalidProperties,
	},
	configs: {},
};

Object.assign(plugin.configs, {
	recommended: {
		plugins: { css: plugin },
		rules: {
			"css/no-empty-blocks": "error",
			"css/no-duplicate-imports": "error",
			"css/no-invalid-at-rules": "error",
			"css/no-invalid-properties": "error",
		},
	},
});
```

with this block:

```
const plugin = {
	meta: {
		name: "@eslint/css",
		version: "0.1.0", // x-release-please-version
	},
	languages: {
		css: new CSSLanguage(),
	},
	rules: {
		"no-empty-blocks": noEmptyBlocks,
		"no-duplicate-imports": noDuplicateImports,
		"no-invalid-at-rules": noInvalidAtRules,
		"no-invalid-properties": noInvalidProperties,
	},
	configs: {
            recommended: {
		rules: {
			"css/no-empty-blocks": "error",
			"css/no-duplicate-imports": "error",
			"css/no-invalid-at-rules": "error",
			"css/no-invalid-properties": "error",
		},
            },
        },
};

Object.assign(plugin.configs.recommended, {
	plugins: { css: plugin },
});
```

### What did you expect to happen?

I expected the typescript types file for the plugin to more specifically provide the type of the recommended configuration.

### What actually happened?

The typescript types file provides the type `{}` for the recommended configuration.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/vitejs-vite-tqjdrtbx?file=eslint.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by fasttime** [comment]
Thanks for the issue @timheilman, I can reproduce the problem with your config file. This should have been fixed already by #16 but we haven't released an updated version of the package yet.
